### ISSUE TITLE
Not getting any output

### ISSUE THREAD

**Issue by Mayank1403** [shibing624/title-generator#1]

**Comment by Mayank1403** [comment]
I tried your code, but unfortunately I am not getting any output no matte what I enter as input.

**Comment by shibing624** [comment]
your should use the right tensorflow version(1.9.0), and check the right model file.

now the input train file is a toy data, the train model maybe Unavailable.

**Comment by Mayank1403** [comment]
I followed instructions provided by you. First using train.py and then
infer.py But when I run infer.py I get blank output.

I didn't understand one command on the instructions that instructed to
paste some txt file some where.

Please help. I need to run this badly

**Comment by shibing624** [comment]
i will update this repo this week.

**Comment by amelieyu1989** [comment]
i get no output either. have you got the right way?

**Comment by amelieyu1989** [comment]
in precise, i got output:UNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKs

**Comment by hdsouza06** [comment]
Even I get the same Output :

output:UNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKs

**Comment by hdsouza06** [comment]
@shibing624  Possible to help ?

**Comment by shibing624** [comment]
fix with https://github.com/shibing624/title-generator/commit/63585aeb8e4ecdf65d508a89109d1130dbdab258
